# Generated by Django 5.0.6 on 2024-05-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciclo',
            old_name='descrpcion',
            new_name='descripcion',
        ),
    ]
