# Generated by Django 5.0.6 on 2024-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraDeArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('en_venta', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='obras/')),
            ],
        ),
    ]
