# Generated by Django 5.0.6 on 2024-06-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_obradearte_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obradearte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
