# Generated by Django 5.0.6 on 2024-06-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_rename_description_meme_descripcion_meme_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='created_at',
            new_name='fecha',
        ),
    ]
