# Generated by Django 5.0.6 on 2024-06-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('rock', 'Rock'), ('rap', 'Rap'), ('reggae', 'Reggae'), ('r&b', 'R&B'), ('jazz', 'Jazz')], max_length=200)),
                ('archivo', models.FileField(upload_to='music_files/')),
            ],
        ),
    ]
