# Generated by Django 5.0.6 on 2024-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('cover_photo', models.ImageField(upload_to='cover_photos/')),
                ('detail_photo', models.ImageField(upload_to='detail_photos/')),
            ],
        ),
    ]
