# Generated by Django 5.0.6 on 2024-05-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.URLField()),
                ('description', models.TextField()),
                ('start_season', models.DateField()),
                ('end_season', models.DateField()),
                ('available_all_year', models.BooleanField(default=False)),
            ],
        ),
    ]
